# Site configuration collection set

title:
email: gundralaa@berkeley.edu
author_name: Abhinav Gundrala
description: |
  My personal blog site for personal projects and experience.
  See what I'm up to!
github_username: gundralaa
show_excerpts: true

# Pages
header_pages:
  - index.md
  - about.md
  - teaching.md
  - projects.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
